name: 'moveCards'
description: 'move a card in teh project toa specific column'
inputs:
  projectNAme:  # id of input
    description: 'name of the target project'
    required: true
    default: ''
  github_token:
    description: GitHub token.
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
