name: 'moveCards'
description: 'move a card in teh project toa specific column'
inputs:
  project_number:  # id of input
    description: 'number of the target project'
    required: true
  target_col:
    description: 'name od the target status (Colum)'
    required: true
  github_token:
    description: GitHub token.
    required: true
  user_name:
    description: user Name.
    required: false
    default: ''
  personal_token:
    description: personal_token.
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
